### ISSUE TITLE
[feature request]close the tab

### ISSUE THREAD

**Issue by anne43983959** [EnsignMK/sd_shutdown_button#2]
looking forward to add a feature to close the browser's tabs while closing the console, but do not directly kill the browser's processes

**Comment by EnsignMK** [comment]
@anne43983959  Sorry for the late reply ,  close the tab is a nice feature I agree, it was in this extension, but it doesn't  work nicely with all the browsers, it sometimes works  and sometimes it doesn't.  


I have been working on other methods, so if the users presses exit button,  the page turns to this:
<img width="935" alt="image" src="https://github.com/EnsignMK/sd_shutdown_button/assets/91480302/b20cd693-fe79-4386-9e10-babc99a2b7d5">

what do you think it about it? 
ps.(that color is still work in progress lol)

**Comment by EnsignMK** [comment]
@anne43983959 see the new update , close tab is supported
